docs: repair broken links and update content in the articles
Open-Attestation/documentation-website pull request #193
Opened 2024-01-22 08:07 UTC by rollerchloe

2024-02-18 15:04 UTC, yapyuyou requested changes

2024-02-19 01:42 UTC, rollerchloe commented on website/docs/ethereum-section/raw-document-eth.md
> +In this guide, you will create a raw document for Ethereum. It will conform to the OpenAttestation v2.0 schema.
Thanks for reviewing! Updated.

2024-02-19 01:57 UTC, rollerchloe commented on website/src/reusables/_wrap-document-intro.mdx
> +Every OA document has a checksum that provides it a tamper-proof property. At the same time, because the checksum can be used to uniquely identify a document, the checksum (or its derived value) is s
`_raw-document.mdx` was created to duplicate the intro in [Creating Raw Document](https://www.openattestation.com/docs/integrator-section/verifiable-document/ethereum/raw-document). 
`_wrap-document-intro.mdx` was duplicating the intro in [Wrapping Documents](https://www.openattestation.com/docs/integrator-section/verifiable-document/ethereum/wrapping-document). 

The intros in the two articles have some overlap, which talks about how a raw document becomes a wrapped doc.

To remove the overlap, I modified `_wrap-document-intro.mdx`, then reference the two MDX files in both articles.

2024-02-19 01:59 UTC, rollerchloe commented on website/docs/prereq-section/prerequisites.md
> +You need to define the revocation method at the point of issuance. For more information, see the [Differences between revocation methods](/docs/revoke-section/diff-btw-revocation-methods) article.
added

2024-02-21 03:32 UTC, yapyuyou approved these changes

2024-02-21 03:35 UTC, merged